
%project_path = 'E:\Seafile\Work_files\Matlab\KU\Projects\Particle_quantification_elongated_structures';
project_path = 'F:\Martin_B_S\Matlab\KU\Projects\Particle_quantification_elongated_structures';

eval(['mcc -o muscleFiberAnalysis ' ... 
      '-W ''WinMain:exe_test,version=1.0'' ' ... 
      '-T link:exe ' ... 
      '-d ' project_path '\Standalone_software\muscleFibreAnalysis_exe ' ...
      '-v ' project_path '\muscleFibreAnalysis.m ' ...
      '-r ''C:\Program Files\MATLAB\R2021b\toolbox\compiler\resources\Matlab_Logo.ico''']);      
%       '-a ' project_path '\External_functions\cart2homo.m ' ...
%       '-a ' project_path '\External_functions\get_rotation_matrix.m ' ...
%       '-a ' project_path '\External_functions\homo2cart.m ' ...
%       '-a ' project_path '\External_functions\rotatePointCloudAlongZ.m ' ...
%       '-a ' project_path '\External_functions\transform_pointset.m ' ...
%       '-a ' project_path '\External_functions\transform_surface.m ' ...
      


